services:
  fcgi:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    # Явно указываем порт для доступа из Apache
    expose:
      - "1337"

  httpd:
    image: "httpd:2.4.62"
    ports:
      - "8080:80"
    volumes:
      - "./httpd.conf:/usr/local/apache2/conf/httpd.conf"
      - "./static:/var/www"
    networks:
      - backend
    depends_on:
      - fcgi

networks:
  backend:
    driver: bridge